In [2]:
import numpy as np
import pandas as pd

In [3]:
np.array([1,2,3])

array([1, 2, 3])

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [7]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.random.rand(3)

array([0.24716447, 0.31900565, 0.61222368])

In [10]:
np.random.rand(5,3)

array([[0.63639727, 0.20296478, 0.74330609],
       [0.08916705, 0.59982814, 0.67751279],
       [0.43895172, 0.54884616, 0.85485892],
       [0.71730712, 0.01254666, 0.5293504 ],
       [0.80799214, 0.75116058, 0.27001002]])

In [11]:
np.random.randint(1,100,10)

array([79, 32, 10, 29, 90, 16, 19, 38, 37, 42])

In [14]:
list1 = [0,5,1,9,6,4,2]

In [15]:
array1 = np.array(list1)

In [19]:
array1.max()

9

In [20]:
array1.argmax()

3

In [21]:
array1.dtype

dtype('int32')

In [22]:
label1 = ['a','b','c']
list2 = [10,20,30]
dict1 = {'a':10,'b':20,'c':30}

In [23]:
array2 = np.array(list2)

In [24]:
pd.Series(data = list2)

0    10
1    20
2    30
dtype: int64

In [25]:
pd.Series(data = list2, index = label1)

a    10
b    20
c    30
dtype: int64

In [26]:
pd.Series(array2,label1)

a    10
b    20
c    30
dtype: int32

In [27]:
pd.Series(dict1)

a    10
b    20
c    30
dtype: int64

In [29]:
ser1 = pd.Series([1,2,3,4],index=["US","GE","TH","JP"])
ser1

US    1
GE    2
TH    3
JP    4
dtype: int64

In [30]:
ser1.sum()

10

In [31]:
ser1.max()

4

In [32]:
ser1.idxmax()

'JP'

In [33]:
ser2 = pd.Series([1,2,3,9],index=["US","GE","TH","UK"])
ser2

US    1
GE    2
TH    3
UK    9
dtype: int64

In [34]:
ser1 + ser2

GE    4.0
JP    NaN
TH    6.0
UK    NaN
US    2.0
dtype: float64

In [35]:
"A B C".split()

['A', 'B', 'C']

In [37]:
df1 = pd.DataFrame(np.random.rand(5,4))
df1

0         1         2         3
0  0.686897  0.048934  0.283383  0.663622
1  0.877838  0.180407  0.524446  0.632051
2  0.854741  0.315569  0.928650  0.241282
3  0.387196  0.002697  0.656183  0.964216
4  0.479856  0.283839  0.380936  0.520184

In [40]:
df1 = pd.DataFrame(np.random.rand(5,4),columns="W X Y Z".split())
df1

W         X         Y         Z
0  0.591806  0.895676  0.343737  0.961024
1  0.425981  0.537441  0.148307  0.548153
2  0.090805  0.508465  0.944894  0.884503
3  0.241629  0.546467  0.480325  0.918949
4  0.398690  0.841037  0.393355  0.163418

In [42]:
df1 = pd.DataFrame(np.random.rand(5,4),index="A B C D E".split(),columns="W X Y Z".split())
df1

W         X         Y         Z
A  0.368907  0.615014  0.936306  0.049011
B  0.268860  0.316095  0.598061  0.167353
C  0.250829  0.282050  0.927114  0.703244
D  0.197332  0.142262  0.841720  0.980352
E  0.065172  0.857956  0.298820  0.543980

In [43]:
df1["W"]

A    0.368907
B    0.268860
C    0.250829
D    0.197332
E    0.065172
Name: W, dtype: float64

In [44]:
df1.W

A    0.368907
B    0.268860
C    0.250829
D    0.197332
E    0.065172
Name: W, dtype: float64

In [46]:
df1[["W","Z"]]

W         Z
A  0.368907  0.049011
B  0.268860  0.167353
C  0.250829  0.703244
D  0.197332  0.980352
E  0.065172  0.543980

In [47]:
df1["ZZ"] = 0
df1

W         X         Y         Z  ZZ
A  0.368907  0.615014  0.936306  0.049011   0
B  0.268860  0.316095  0.598061  0.167353   0
C  0.250829  0.282050  0.927114  0.703244   0
D  0.197332  0.142262  0.841720  0.980352   0
E  0.065172  0.857956  0.298820  0.543980   0

In [49]:
df1["W"]+df1["X"]

A    0.983921
B    0.584955
C    0.532879
D    0.339594
E    0.923128
dtype: float64

In [51]:
df1["WX"] = df1["W"]+df1["X"]

In [52]:
df1

W         X         Y         Z  ZZ        WX
A  0.368907  0.615014  0.936306  0.049011   0  0.983921
B  0.268860  0.316095  0.598061  0.167353   0  0.584955
C  0.250829  0.282050  0.927114  0.703244   0  0.532879
D  0.197332  0.142262  0.841720  0.980352   0  0.339594
E  0.065172  0.857956  0.298820  0.543980   0  0.923128

In [55]:
df1.drop("ZZ",axis=1)

W         X         Y         Z        WX
A  0.368907  0.615014  0.936306  0.049011  0.983921
B  0.268860  0.316095  0.598061  0.167353  0.584955
C  0.250829  0.282050  0.927114  0.703244  0.532879
D  0.197332  0.142262  0.841720  0.980352  0.339594
E  0.065172  0.857956  0.298820  0.543980  0.923128

In [56]:
df1.drop("E",axis=0)

W         X         Y         Z  ZZ        WX
A  0.368907  0.615014  0.936306  0.049011   0  0.983921
B  0.268860  0.316095  0.598061  0.167353   0  0.584955
C  0.250829  0.282050  0.927114  0.703244   0  0.532879
D  0.197332  0.142262  0.841720  0.980352   0  0.339594

In [57]:
df1.drop("ZZ",axis=1,inplace=True)

In [58]:
df1 = df1.drop("E",axis=0)

In [59]:
df1

W         X         Y         Z        WX
A  0.368907  0.615014  0.936306  0.049011  0.983921
B  0.268860  0.316095  0.598061  0.167353  0.584955
C  0.250829  0.282050  0.927114  0.703244  0.532879
D  0.197332  0.142262  0.841720  0.980352  0.339594

In [60]:
df1.loc["A"]

W     0.368907
X     0.615014
Y     0.936306
Z     0.049011
WX    0.983921
Name: A, dtype: float64

In [61]:
df1.iloc[2]

W     0.250829
X     0.282050
Y     0.927114
Z     0.703244
WX    0.532879
Name: C, dtype: float64

In [62]:
df1.loc["A","W"]

0.36890651345645864

In [63]:
df1.loc[["B","C"],["X","Y"]]

X         Y
B  0.316095  0.598061
C  0.282050  0.927114

In [64]:
df1>1

W      X      Y      Z     WX
A  False  False  False  False  False
B  False  False  False  False  False
C  False  False  False  False  False
D  False  False  False  False  False

In [65]:
df1>0

W     X     Y     Z    WX
A  True  True  True  True  True
B  True  True  True  True  True
C  True  True  True  True  True
D  True  True  True  True  True

In [66]:
df1>0.5

W      X     Y      Z     WX
A  False   True  True  False   True
B  False  False  True  False   True
C  False  False  True   True   True
D  False  False  True   True  False

In [67]:
df1[df1>0.5]

W         X         Y         Z        WX
A NaN  0.615014  0.936306       NaN  0.983921
B NaN       NaN  0.598061       NaN  0.584955
C NaN       NaN  0.927114  0.703244  0.532879
D NaN       NaN  0.841720  0.980352       NaN

In [69]:
df1[df1.Y>0.5]

W         X         Y         Z        WX
A  0.368907  0.615014  0.936306  0.049011  0.983921
B  0.268860  0.316095  0.598061  0.167353  0.584955
C  0.250829  0.282050  0.927114  0.703244  0.532879
D  0.197332  0.142262  0.841720  0.980352  0.339594

In [71]:
df1[df1["Y"]>0.5]

W         X         Y         Z        WX
A  0.368907  0.615014  0.936306  0.049011  0.983921
B  0.268860  0.316095  0.598061  0.167353  0.584955
C  0.250829  0.282050  0.927114  0.703244  0.532879
D  0.197332  0.142262  0.841720  0.980352  0.339594

In [73]:
df1[(df1["W"]>0.3)&(df1["X"]>0.3)]

W         X         Y         Z        WX
A  0.368907  0.615014  0.936306  0.049011  0.983921


### <span style=color:red>If there are data more than 800,000, You can't use DataFrame.</span>

In [74]:
df2 = pd.read_csv("D:/_meowppp/test/jupyter notebook/ProgressOfMyDataScience/test0211.csv")

In [75]:
df2

num    name  stupid score(100)  your score(5)
0    1  Prayut                100              0
1    2     Pom                 99              0
2    3  Snoopy                 30              4

In [76]:
df3 = pd.read_csv("D:/_meowppp/test/jupyter notebook/ProgressOfMyDataScience/test0212.csv")

In [77]:
df3["vat"] = df3["price"]*0.07

In [81]:
df3

no         name category  price     vat
0   1      GamePad   widget  20.25  1.4175
1   2  GameConsole   Device  59.99  4.1993
2   3   GameScreen  Monitor  30.00  2.1000
3   4      GameJoy   widget  19.75  1.3825

In [85]:
df3.to_csv("D:/_meowppp/test/jupyter notebook/ProgressOfMyDataScience/test0212-2.csv", index = False)

In [93]:
df3.groupby("category").sum()

no  price     vat
category                   
Device     2  59.99  4.1993
Monitor    3  30.00  2.1000
widget     5  40.00  2.8000

In [94]:
df3.groupby("category").max()

no         name  price     vat
category                                
Device     2  GameConsole  59.99  4.1993
Monitor    3   GameScreen  30.00  2.1000
widget     4      GamePad  20.25  1.4175

In [95]:
df3.groupby("category").mean()

no  price     vat
category                    
Device    2.0  59.99  4.1993
Monitor   3.0  30.00  2.1000
widget    2.5  20.00  1.4000

In [96]:
df3.sort_values("price")

no         name category  price     vat
3   4      GameJoy   widget  19.75  1.3825
0   1      GamePad   widget  20.25  1.4175
2   3   GameScreen  Monitor  30.00  2.1000
1   2  GameConsole   Device  59.99  4.1993

In [97]:
df3.sort_values("price", ascending = False)

no         name category  price     vat
1   2  GameConsole   Device  59.99  4.1993
2   3   GameScreen  Monitor  30.00  2.1000
0   1      GamePad   widget  20.25  1.4175
3   4      GameJoy   widget  19.75  1.3825

In [98]:
df3.sort_values(["price","vat"])

no         name category  price     vat
3   4      GameJoy   widget  19.75  1.3825
0   1      GamePad   widget  20.25  1.4175
2   3   GameScreen  Monitor  30.00  2.1000
1   2  GameConsole   Device  59.99  4.1993

In [99]:
df3["category"].unique()

array(['widget', 'Device', 'Monitor'], dtype=object)

In [100]:
def times2(x):
    return x*2

In [101]:
times2(5)

10

In [102]:
times2(df3["price"])

0     40.50
1    119.98
2     60.00
3     39.50
Name: price, dtype: float64

In [103]:
df3["price"].apply(times2)

0     40.50
1    119.98
2     60.00
3     39.50
Name: price, dtype: float64

In [105]:
len(df3["category"])

4

In [106]:
df3["category"].apply(len)

0    6
1    6
2    7
3    6
Name: category, dtype: int64

In [107]:
df3.sum()

no                                           10
name        GamePadGameConsoleGameScreenGameJoy
category              widgetDeviceMonitorwidget
price                                    129.99
vat                                      9.0993
dtype: object

In [108]:
df3.max()

no                   4
name        GameScreen
category        widget
price            59.99
vat             4.1993
dtype: object

In [109]:
df3.min()

no                    1
name        GameConsole
category         Device
price             19.75
vat              1.3825
dtype: object

In [110]:
df3.mean()

no        2.500000
price    32.497500
vat       2.274825
dtype: float64

In [114]:
df3.loc[1,"price"] = np.NaN

In [115]:
df3

no         name category  price     vat
0   1      GamePad   widget  20.25  1.4175
1   2  GameConsole   Device    NaN  4.1993
2   3   GameScreen  Monitor  30.00  2.1000
3   4      GameJoy   widget  19.75  1.3825

In [116]:
df3.loc[1,"price"] = 60.00

In [117]:
df3

no         name category  price     vat
0   1      GamePad   widget  20.25  1.4175
1   2  GameConsole   Device  60.00  4.1993
2   3   GameScreen  Monitor  30.00  2.1000
3   4      GameJoy   widget  19.75  1.3825

In [118]:
df3.loc[0,"price"] = np.NaN

In [120]:
df3.dropna(inplace=True)

In [121]:
df3

no         name category  price     vat
1   2  GameConsole   Device  60.00  4.1993
2   3   GameScreen  Monitor  30.00  2.1000
3   4      GameJoy   widget  19.75  1.3825

In [125]:
df3.loc[2,"no"] = np.NaN

In [126]:
df3.fillna(0)

no         name category  price     vat
1  2.0  GameConsole   Device  60.00  4.1993
2  0.0   GameScreen  Monitor  30.00  2.1000
3  4.0      GameJoy   widget  19.75  1.3825

In [129]:
df3.loc[2,"no"] = np.NaN

In [130]:
df3.fillna(df3.no.mean())

no         name category  price     vat
1  2.0  GameConsole   Device  60.00  4.1993
2  2.0   GameScreen  Monitor  30.00  2.1000
3  2.0      GameJoy   widget  19.75  1.3825

In [131]:
df3["vat"].round(2)

1    4.20
2    2.10
3    1.38
Name: vat, dtype: float64

In [132]:
df4 = pd.read_csv("D:/_meowppp/test/jupyter notebook/ProgressOfMyDataScience/test0212-3.csv")

In [134]:
for index, row in df4.iterrows():
    print(index,row["name"])
    df4.loc[index,"vat"]=0

0 Sony SmartTV
1 Samsung SmartTV
2 IPhone
3 Galaxy S20
4 IPad
